Output demo.gif

Set Theme "Catppuccin Mocha"
Set FontSize 16
Set Width 750
Set Height 450
Set Padding 30

Type "cd .."
Enter
Sleep 1s

Type "purr init"
Enter
Sleep 2s

Enter
Sleep 500ms

Type "purr add ."
Enter
Sleep 3s

Enter
Sleep 500ms

Type "purr ls"
Enter
Sleep 4s

Enter
Sleep 500ms

Type "purr commit -m "
Type '"initial commit"'
Enter
Sleep 3s

Enter
Sleep 500ms

Type "purr log"
Enter
Sleep 5s

